Release 1.7.0 Beta
NewSpring/crete pull request #138
Opened 2020-10-29 19:14 UTC by vinnyjth

## DESCRIPTION

### What does this PR do, or why is it needed?

### How do I test this PR?

## TODO

- [ ] I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))
- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] No new warnings
- [ ] Upload Screenshots/GIF(s) if applicable
- [ ] Set a relevant reviewer

## REVIEW

- [ ] Review updates to test coverage and snapshots
- [ ] Review code through the lens of being concise, simple, and well-documented

---

> The purpose of a PR Review is to _improve the quality of the software._

2020-11-03 18:36 UTC, briankalwat requested changes
@vinnyjth seeing a few issues initially while running these changes, specifically with the home feed:
- New feature block directly above the events block.
![image](https://user-images.githubusercontent.com/2465823/98024574-7ea6ce80-1dd6-11eb-936c-9ce3169d1c89.png)
- New feature block directly after next steps block that looks like it includes all home feed content items.
![image](https://user-images.githubusercontent.com/2465823/98024618-8ebeae00-1dd6-11eb-94c9-b1febf829c99.png)

2020-11-04 13:20 UTC, vinnyjth commented
@briankalwat Thanks Brian! I think I fixed that in a commit that you must not have locally. Can you try pulling the latest code and give it another shot? 

<img width="570" alt="Screen Shot 2020-11-04 at 8 19 08 AM" src="https://user-images.githubusercontent.com/1637694/98116658-95046700-1e76-11eb-94c5-dbb16f19a2d1.png">

2020-11-04 14:28 UTC, briankalwat submitted a review, later dismissed
Looks like everything appears normal now.

2020-11-04 16:15 UTC, vinnyjth commented on config.yml
> +        name: Storeis
```suggestion
        name: Stories        
```
typo

2020-11-04 18:03 UTC, vinnyjth commented
@briankalwat Can you please re-approve? I believe I dismissed your review by fixing a typo :)

2020-11-05 13:22 UTC, briankalwat approved these changes

2020-11-05 16:03 UTC, vinnyjth commented
@briankalwat Okay, I'll need your approval one more time. I had to push some more test to make sure we are at 100% coverage. 

I think we could look at turning off "stale review dismissal" if that's okay with you. I think you can do it from the branch protection settings.

2020-11-05 16:28 UTC, briankalwat approved these changes

2020-11-05 16:34 UTC, merged